# Use PHP provider with Node added
providers = ["php"]

[phases.setup]
nixPkgs = ["nodejs_20", "nginx"]

[phases.install]
cmds = ["npm install", "mkdir -p /app/storage/logs"]

[start]
cmd = "node bot.js & node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"

[variables]
PORT = "8080"
