[start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf & npm install && node bot.js)"

[variables]
PORT = "8080"
